class BotNameGenerator
{
	static ref array<string> m_NameS = new array<string>;
	
	static void BotNameGeneratorInsert()
	{
		m_NameS.Insert("Лысый");
		m_NameS.Insert("Гуцул");
		m_NameS.Insert("Цыган");
		m_NameS.Insert("Академик");
		m_NameS.Insert("Арап");
		m_NameS.Insert("Зима");
		m_NameS.Insert("Крученый");
		m_NameS.Insert("Курок");
		m_NameS.Insert("Чирий");
		m_NameS.Insert("Трэш");
		m_NameS.Insert("Тыр");
		m_NameS.Insert("Клямпер");
		m_NameS.Insert("Мальчик");
		m_NameS.Insert("Кривой");
		m_NameS.Insert("Бэн");
		m_NameS.Insert("Силя");
		m_NameS.Insert("Пашканчик");
		m_NameS.Insert("Миша - терминатор");
		m_NameS.Insert("Батон");
		m_NameS.Insert("Кот");
		m_NameS.Insert("Сика");
		m_NameS.Insert("Шапито");
		m_NameS.Insert("Репа");
		m_NameS.Insert("Мозг");
		m_NameS.Insert("Боров");
		m_NameS.Insert("Свин");
		m_NameS.Insert("Свинец");
		m_NameS.Insert("Навзик");
		m_NameS.Insert("Чиж");
		m_NameS.Insert("Лещ");
		m_NameS.Insert("Чиркан");
		m_NameS.Insert("Молодой");
		m_NameS.Insert("Панк");
		m_NameS.Insert("Пышный");
		m_NameS.Insert("Бух");
		m_NameS.Insert("Бокс");
		m_NameS.Insert("Губастый");
		m_NameS.Insert("Клюй");
		m_NameS.Insert("Васек");
		m_NameS.Insert("Крыл");
		m_NameS.Insert("Нос");
		m_NameS.Insert("Фрол");
		m_NameS.Insert("Базай");
		m_NameS.Insert("Воробей");
		m_NameS.Insert("Питон");
		m_NameS.Insert("Люссак");
		m_NameS.Insert("Пидаль");
		m_NameS.Insert("Блин");
		m_NameS.Insert("Федот");
		m_NameS.Insert("Боб");
		m_NameS.Insert("Зевс");
		m_NameS.Insert("Кабан");
		m_NameS.Insert("Ашот");
		m_NameS.Insert("Саша Белый");
		m_NameS.Insert("Олег на Читырке");
		m_NameS.Insert("Адрей");
		m_NameS.Insert("Дин Холл");
		m_NameS.Insert("Славаукраиский");
		m_NameS.Insert("Пупкин");
		m_NameS.Insert("Горемыкин");
		m_NameS.Insert("Дрочилин");
		m_NameS.Insert("Дрочилин");
		m_NameS.Insert("Забабахин");
		m_NameS.Insert("Херович");
		m_NameS.Insert("Гнилосыр");
		m_NameS.Insert("Блудов");
		m_NameS.Insert("Херович");
		m_NameS.Insert("Жаба");
		m_NameS.Insert("Блатнов");
		m_NameS.Insert("Мясной");
		m_NameS.Insert("Сорвирогов");
		m_NameS.Insert("Новодранов");
		m_NameS.Insert("Терпигорев");
		m_NameS.Insert("Мерлинов");
		m_NameS.Insert("Пендерас");
		m_NameS.Insert("Потеряхин");
		m_NameS.Insert("Голопузиков");
		m_NameS.Insert("Колобов");
		m_NameS.Insert("Анимэ");
		m_NameS.Insert("Жирик");
		m_NameS.Insert("Руся");
		m_NameS.Insert("ПриораЧёрный");
		m_NameS.Insert("Меридиан");
		m_NameS.Insert("Бездушный");
		m_NameS.Insert("Жирноносов");
		m_NameS.Insert("Безумнов");
		m_NameS.Insert("Блюваль");
		m_NameS.Insert("Сатанищев");
		m_NameS.Insert("Вревский");
		m_NameS.Insert("Мумриков");
		m_NameS.Insert("Горемыкин");
		m_NameS.Insert("Лихопой");
		m_NameS.Insert("Беломоров");
		m_NameS.Insert("Забабахин");
		m_NameS.Insert("Дармоедов");
		m_NameS.Insert("Облеухов");
		m_NameS.Insert("Мудеев");
		m_NameS.Insert("Срулев");
		m_NameS.Insert("Магазинер");
		m_NameS.Insert("Невежин");
		m_NameS.Insert("Сиволап");
		m_NameS.Insert("Терпигорев");
		m_NameS.Insert("Голубец");
		m_NameS.Insert("Велес");
		m_NameS.Insert("Дармоедов");
	}
	
	static string GetNameRandom()
	{
		return m_NameS.Get(Math.RandomInt(0,m_NameS.Count()));
	}
};